
    using Microsoft.Build.Framework;
    using Microsoft.Build.Utilities;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;

    namespace RizzyUI.Tasks;

    public sealed class GenerateCollocatedModuleMapTask : Task
    {
        [Required]
        public ITaskItem[] RazorFiles { get; set; } = Array.Empty<ITaskItem>();

        [Required]
        public string ProjectDirectory { get; set; } = string.Empty;
        
        [Required]
        public string RootNamespace { get; set; } = string.Empty;

        [Required]
        public string IntermediateOutputPath { get; set; } = string.Empty;
        
        [Required]
        public string StaticWebAssetBasePath { get; set; } = string.Empty;

        [Output]
        public string GeneratedSourceFile { get; set; } = string.Empty;

        private static readonly Regex NamespaceRegex = new Regex(@"@namespace\s+([a-zA-Z0-9_.]+)");

        public override bool Execute()
        {
            var moduleMap = new Dictionary<string, string>();

            foreach (var razorFileItem in RazorFiles)
            {
                var razorFilePath = razorFileItem.GetMetadata("FullPath");
                if (!File.Exists(razorFilePath)) continue;

                var jsFilePath = Path.ChangeExtension(razorFilePath, ".razor.js");
                if (!File.Exists(jsFilePath)) continue;

                var fileContent = File.ReadAllText(razorFilePath);
                if (!fileContent.Contains("[DiscoverCollocatedJS]")) continue;

                var componentTypeName = GetComponentTypeName(razorFilePath, fileContent);
                if (string.IsNullOrEmpty(componentTypeName))
                {
                    Log.LogWarning($"Could not determine full type name for component with collocated JS: {razorFilePath}");
                    continue;
                }

                var relativeJsPath = GetRelativePath(ProjectDirectory, jsFilePath).Replace(Path.DirectorySeparatorChar, '/');
                var webPath = $"/{StaticWebAssetBasePath}/{relativeJsPath}".Replace("//", "/");

                moduleMap[componentTypeName] = webPath;
            }

            if (moduleMap.Any())
            {
                GeneratedSourceFile = Path.Combine(IntermediateOutputPath, "RizzyUI.CollocatedModules.g.cs");
                var sourceCode = GenerateCSharpSource(moduleMap);
                File.WriteAllText(GeneratedSourceFile, sourceCode);
            }

            return !Log.HasLoggedErrors;
        }

        private string GetComponentTypeName(string razorFilePath, string fileContent)
        {
            var fileName = Path.GetFileNameWithoutExtension(razorFilePath);
            var namespaceMatch = NamespaceRegex.Match(fileContent);
            if (namespaceMatch.Success)
            {
                return $"{namespaceMatch.Groups[1].Value}.{fileName}";
            }

            var relativeDir = Path.GetDirectoryName(GetRelativePath(ProjectDirectory, razorFilePath));
            var namespaceFromPath = string.IsNullOrEmpty(relativeDir) ? RootNamespace : $"{RootNamespace}.{relativeDir.Replace(Path.DirectorySeparatorChar, '.')}";
            
            return $"{namespaceFromPath}.{fileName}";
        }

        private string GenerateCSharpSource(Dictionary<string, string> moduleMap)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            sb.AppendLine("internal static class RizzyUI_ModuleInitializer");
            sb.AppendLine("{");
            sb.AppendLine("    [ModuleInitializer]");
            sb.AppendLine("    public static void Initialize()");
            sb.AppendLine("    {");

            foreach (var entry in moduleMap)
            {
                sb.AppendLine($"        RizzyUI.RzAlpineModuleRegistry.Add(\"{entry.Key}\", \"{entry.Value}\");");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GetRelativePath(string relativeTo, string path)
        {
            var uri = new Uri(relativeTo.EndsWith(Path.DirectorySeparatorChar.ToString()) ? relativeTo : relativeTo + Path.DirectorySeparatorChar);
            var relUri = uri.MakeRelativeUri(new Uri(path));
            return Uri.UnescapeDataString(relUri.ToString());
        }
    }