using System.Web;
using Rizzy.Utility;
using RizzyUI.Extensions;
using Microsoft.AspNetCore.Components;
using Markdig;

namespace RizzyUI;

/// <xmldoc>
/// A Markdown component that converts the provided RenderFragment markdown content into HTML.
/// The markdown content is passed as child content and converted to HTML using Markdig.
/// </xmldoc>
public partial class Markdown : RizzyComponent
{
    private static readonly string BaseStyle = "prose lg:prose-xl";

    /// <xmldoc>
    /// Gets or sets the html-encoded markdown content provided as child content.
    /// </xmldoc>
    [Parameter]
    public RenderFragment? ChildContent { get; set; }

    /// <xmldoc>
    /// Gets the HTML markup generated by converting the markdown content.
    /// </xmldoc>
    private MarkupString OutputHtml { get; set; }

    /// <xmldoc>
    /// Computes the final CSS class string for the root element by merging AdditionalAttributes with the base style.
    /// </xmldoc>
    protected override string? RootClass() => TwMerge.Merge(AdditionalAttributes, BaseStyle);

    /// <xmldoc>
    /// Called when component parameters have been set. Converts the markdown content (via AsMarkupString())
    /// into HTML using Markdig and stores it in OutputHtml.
    /// </xmldoc>
    protected override void OnParametersSet()
    {
        base.OnParametersSet();

        // Use the extension method from Rizzy.Extensions to get the markdown text.
        string markdownText = ChildContent?.AsMarkupString().Outdent() ?? string.Empty;
        markdownText = HttpUtility.HtmlDecode(markdownText);

        // Convert the markdown to HTML using Markdig.
        string html = Markdig.Markdown.ToHtml(markdownText);

        // Wrap the HTML string in a MarkupString so it renders as HTML.
        OutputHtml = new MarkupString(html);
    }
}